"""
Unit tests for ai/extraction_validator.py — Module 2.3b

All tests use synthetic ExtractedClaim objects — no Gemini API key required.
The validator is a pure function so every case is deterministic.
"""

import pytest
from app.ai.extraction_schema import ExtractedClaim, ExtractionOutput
from app.ai.extraction_validator import (
    STATE_CONFLICTING,
    STATE_LOW_CONFIDENCE,
    STATE_SUPPORTED,
    ValidatedClaim,
    validate_and_normalize,
)
from app.parsers.base import ParsedChunk

# ─── Helpers ─────────────────────────────────────────────────────────────────

VALID_KEYS = {"lead_time_days", "capacity_monthly", "iso_9001", "country", "cert_expiry"}


def make_claim(**kwargs) -> ExtractedClaim:
    # Removed page_number, sheet_name, cell_range, section as they are no longer generated by the LLM
    defaults = dict(
        field_key="lead_time_days",
        raw_value="24 days",
        normalized_value=24,
        unit="day",
        confidence=0.95,
        quoted_text="Lead time is 24 days from order confirmation."
    )
    return ExtractedClaim(**{**defaults, **kwargs})


def make_output(*claims: ExtractedClaim) -> ExtractionOutput:
    return ExtractionOutput(claims=list(claims))


def run(output, existing=None):
    # Mock chunks so that quoted text passes deterministic validation
    chunks = []
    for claim in output.claims:
        if claim.quoted_text and claim.quoted_text.strip():
            chunks.append(ParsedChunk(
                text=f"Prefix text {claim.quoted_text} Suffix text",
                section=None,
                page_number=1,
                sheet_name=None,
                cell_range=None
            ))
    return validate_and_normalize(output, VALID_KEYS, parsed_chunks=chunks, existing_claims=existing)


# ─── Gate 1: field_key validation ────────────────────────────────────────────

def test_unknown_field_key_is_rejected():
    claim = make_claim(field_key="unknown_field_xyz")
    report = run(make_output(claim))
    assert len(report.validated) == 0
    assert report.rejected_count == 1
    assert "unknown_field_xyz" in report.rejection_reasons[0]


def test_known_field_key_passes():
    claim = make_claim(field_key="lead_time_days")
    report = run(make_output(claim))
    assert len(report.validated) == 1


# ─── Gate 2: quoted_text validation ──────────────────────────────────────────

def test_empty_quoted_text_is_rejected():
    claim = make_claim(quoted_text="")
    report = run(make_output(claim))
    assert report.rejected_count == 1


def test_whitespace_quoted_text_is_rejected():
    claim = make_claim(quoted_text="   ")
    report = run(make_output(claim))
    assert report.rejected_count == 1


# ─── Value normalization ─────────────────────────────────────────────────────

def test_string_yes_normalized_to_bool_true():
    claim = make_claim(
        field_key="iso_9001",
        normalized_value="yes",
        unit=None,
    )
    report = run(make_output(claim))
    assert report.validated[0].normalized_value is True
    assert report.validated[0].unit is None


def test_string_no_normalized_to_bool_false():
    claim = make_claim(
        field_key="iso_9001",
        normalized_value="no",
        unit=None,
    )
    report = run(make_output(claim))
    assert report.validated[0].normalized_value is False


def test_string_number_with_unit_parsed():
    claim = make_claim(normalized_value="24 days", unit=None)
    report = run(make_output(claim))
    assert report.validated[0].normalized_value == pytest.approx(24.0)
    assert report.validated[0].unit == "day"


def test_numeric_value_passed_through():
    claim = make_claim(normalized_value=25000, unit="unit")
    report = run(make_output(claim))
    assert report.validated[0].normalized_value == 25000


def test_date_string_kept_as_is():
    claim = make_claim(
        field_key="cert_expiry",
        normalized_value="2027-06-30",
        unit=None,
    )
    report = run(make_output(claim))
    assert report.validated[0].normalized_value == "2027-06-30"


# ─── Evidence state assignment ────────────────────────────────────────────────

def test_high_confidence_becomes_supported():
    claim = make_claim(confidence=0.95)
    report = run(make_output(claim))
    assert report.validated[0].state == STATE_SUPPORTED
    assert report.has_low_confidence is False


def test_exactly_at_threshold_becomes_supported():
    claim = make_claim(confidence=0.5)
    report = run(make_output(claim))
    assert report.validated[0].state == STATE_SUPPORTED


def test_below_threshold_becomes_low_confidence():
    claim = make_claim(confidence=0.49)
    report = run(make_output(claim))
    assert report.validated[0].state == STATE_LOW_CONFIDENCE
    assert report.has_low_confidence is True


def test_zero_confidence_becomes_low_confidence():
    claim = make_claim(confidence=0.0)
    report = run(make_output(claim))
    assert report.validated[0].state == STATE_LOW_CONFIDENCE


# ─── Conflict detection ───────────────────────────────────────────────────────

def test_no_conflict_if_same_value():
    prior = ValidatedClaim(
        field_key="lead_time_days", raw_value="24 days", normalized_value=24.0,
        unit="day", state=STATE_SUPPORTED, confidence=0.95,
        quoted_text="Lead time 24 days.", page_number=1,
        sheet_name=None, cell_range=None, section=None,
    )
    claim = make_claim(normalized_value=24, field_key="lead_time_days")
    report = run(make_output(claim), existing=[prior])
    assert report.validated[0].state == STATE_SUPPORTED
    assert report.has_conflicts is False


def test_conflict_detected_different_value():
    prior = ValidatedClaim(
        field_key="lead_time_days", raw_value="24 days", normalized_value=24.0,
        unit="day", state=STATE_SUPPORTED, confidence=0.95,
        quoted_text="Lead time 24 days.", page_number=1,
        sheet_name=None, cell_range=None, section=None,
    )
    claim = make_claim(normalized_value=35, field_key="lead_time_days")
    report = run(make_output(claim), existing=[prior])
    assert report.validated[0].state == STATE_CONFLICTING
    assert prior.state == STATE_CONFLICTING  # retroactive marking
    assert report.has_conflicts is True


def test_low_confidence_does_not_trigger_conflict():
    prior = ValidatedClaim(
        field_key="lead_time_days", raw_value="24 days", normalized_value=24.0,
        unit="day", state=STATE_SUPPORTED, confidence=0.95,
        quoted_text="Lead time 24 days.", page_number=1,
        sheet_name=None, cell_range=None, section=None,
    )
    # Low confidence claim with different value → should NOT mark prior as CONFLICTING
    claim = make_claim(normalized_value=99, confidence=0.3, field_key="lead_time_days")
    report = run(make_output(claim), existing=[prior])
    assert report.validated[0].state == STATE_LOW_CONFIDENCE
    assert prior.state == STATE_SUPPORTED  # must NOT be marked CONFLICTING


# ─── Empty output ─────────────────────────────────────────────────────────────

def test_empty_extraction_output():
    report = run(ExtractionOutput(claims=[]))
    assert report.validated == []
    assert report.rejected_count == 0
    assert report.has_conflicts is False
    assert report.has_low_confidence is False


def test_all_rejected_no_valid_output():
    claim = make_claim(field_key="bad_key")
    report = run(make_output(claim))
    assert len(report.validated) == 0
    assert report.rejected_count == 1


# ─── Deterministic Provenance Pipeline Tests ──────────────────────────────────

def test_validator_pdf_unique_quote():
    chunks = [
        ParsedChunk(text="ISO 9001 Certification, Not Certified, Supplier C does not hold this.", page_number=1, sheet_name=None, cell_range=None, section=None),
        ParsedChunk(text="Other text on page 2.", page_number=2, sheet_name=None, cell_range=None, section=None)
    ]
    claim = make_claim(field_key="iso_9001", raw_value="Not Certified", normalized_value=False, quoted_text="Supplier C does not hold this.")
    report = validate_and_normalize(make_output(claim), VALID_KEYS, chunks)
    
    assert len(report.validated) == 1
    val_claim = report.validated[0]
    assert val_claim.state == "SUPPORTED"
    assert val_claim.page_number == 1
    assert val_claim.sheet_name is None
    assert val_claim.provenance_method == "DETERMINISTIC_QUOTE_MATCH"
    assert val_claim.validation_reason == "UNIQUE_SOURCE_MATCH"

def test_validator_xlsx_unique_quote():
    chunks = [
        ParsedChunk(text="ISO 9001 Certification, Not Certified, Supplier C does not hold this.", page_number=None, sheet_name="Compliance", cell_range="A3:C3", section=None),
    ]
    claim = make_claim(field_key="iso_9001", raw_value="Not Certified", normalized_value=False, quoted_text="Supplier C does not hold this.")
    report = validate_and_normalize(make_output(claim), VALID_KEYS, chunks)
    
    val_claim = report.validated[0]
    assert val_claim.state == "SUPPORTED"
    assert val_claim.page_number is None
    assert val_claim.sheet_name == "Compliance"
    assert val_claim.cell_range == "A3:C3"
    assert val_claim.provenance_method == "DETERMINISTIC_QUOTE_MATCH"
    assert val_claim.validation_reason == "UNIQUE_SOURCE_MATCH"

def test_validator_missing_quote():
    chunks = [
        ParsedChunk(text="Some other text entirely.", page_number=1, sheet_name=None, cell_range=None, section=None),
    ]
    claim = make_claim(field_key="iso_9001", raw_value="Not Certified", normalized_value=False, quoted_text="Supplier C does not hold this.")
    report = validate_and_normalize(make_output(claim), VALID_KEYS, chunks)
    
    assert len(report.validated) == 1
    val_claim = report.validated[0]
    assert val_claim.state == "LOW_CONFIDENCE"
    assert val_claim.validation_reason == "CITATION_MISMATCH"
    assert report.rejected_count == 1
    assert "CITATION_MISMATCH" in report.rejection_reasons[0]

def test_validator_ambiguous_quote():
    chunks = [
        ParsedChunk(text="Supplier C does not hold this.", page_number=1, sheet_name=None, cell_range=None, section=None),
        ParsedChunk(text="Supplier C does not hold this.", page_number=2, sheet_name=None, cell_range=None, section=None),
    ]
    claim = make_claim(field_key="iso_9001", raw_value="Not Certified", normalized_value=False, quoted_text="Supplier C does not hold this.")
    report = validate_and_normalize(make_output(claim), VALID_KEYS, chunks)
    
    assert len(report.validated) == 1
    val_claim = report.validated[0]
    assert val_claim.state == "LOW_CONFIDENCE"
    assert val_claim.validation_reason == "AMBIGUOUS_CITATION"
    assert report.rejected_count == 1
    assert "AMBIGUOUS_CITATION" in report.rejection_reasons[0]

def test_validator_overlapping_chunks_same_canonical():
    chunks = [
        ParsedChunk(text="Prefix Supplier C does not hold this.", page_number=None, sheet_name="Compliance", cell_range="A3:C3", section=None),
        ParsedChunk(text="Supplier C does not hold this. Suffix.", page_number=None, sheet_name="Compliance", cell_range="A3:C3", section=None),
    ]
    claim = make_claim(field_key="iso_9001", raw_value="Not Certified", normalized_value=False, quoted_text="Supplier C does not hold this.")
    report = validate_and_normalize(make_output(claim), VALID_KEYS, chunks)
    
    assert len(report.validated) == 1
    val_claim = report.validated[0]
    assert val_claim.state == "SUPPORTED"
    assert val_claim.sheet_name == "Compliance"
    assert val_claim.validation_reason == "UNIQUE_SOURCE_MATCH"
