"""initial

Revision ID: bfa38df8b845
Revises: 
Create Date: 2026-08-08 14:49:57.112242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa38df8b845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcing_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('normalization_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sourcing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_scenarios_case_id'), 'ranking_scenarios', ['case_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=10), nullable=True),
    sa.Column('target_value', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sourcing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_case_id'), 'requirements', ['case_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sourcing_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_case_id'), 'suppliers', ['case_id'], unique=False)
    op.create_table('decision_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_supplier_id', sa.String(length=36), nullable=True),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('review_actions', sa.JSON(), nullable=True),
    sa.Column('human_decision', sa.Text(), nullable=True),
    sa.Column('human_decision_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sourcing_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['ranking_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_summaries_case_id'), 'decision_summaries', ['case_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_supplier_id'), 'documents', ['supplier_id'], unique=False)
    op.create_table('eligibility_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=True),
    sa.Column('observed_unit', sa.String(length=50), nullable=True),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sourcing_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_checks_case_id'), 'eligibility_checks', ['case_id'], unique=False)
    op.create_index(op.f('ix_eligibility_checks_requirement_id'), 'eligibility_checks', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_eligibility_checks_supplier_id'), 'eligibility_checks', ['supplier_id'], unique=False)
    op.create_table('eligibility_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('check_ids', sa.JSON(), nullable=True),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['sourcing_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_results_case_id'), 'eligibility_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_eligibility_results_supplier_id'), 'eligibility_results', ['supplier_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_document_id'), 'extraction_runs', ['document_id'], unique=False)
    op.create_table('ranking_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('eligibility_result_id', sa.String(length=36), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('ranking_version', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eligibility_result_id'], ['eligibility_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['ranking_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_results_scenario_id'), 'ranking_results', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_ranking_results_supplier_id'), 'ranking_results', ['supplier_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_run_id', sa.String(length=36), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('cell_range', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('retrieval_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_evidence_extraction_run_id'), 'evidence', ['extraction_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_field_key'), 'evidence', ['field_key'], unique=False)
    op.create_index(op.f('ix_evidence_supplier_id'), 'evidence', ['supplier_id'], unique=False)
    op.create_table('score_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ranking_result_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ranking_result_id'], ['ranking_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_components_ranking_result_id'), 'score_components', ['ranking_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_components_ranking_result_id'), table_name='score_components')
    op.drop_table('score_components')
    op.drop_index(op.f('ix_evidence_supplier_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_field_key'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_extraction_run_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_ranking_results_supplier_id'), table_name='ranking_results')
    op.drop_index(op.f('ix_ranking_results_scenario_id'), table_name='ranking_results')
    op.drop_table('ranking_results')
    op.drop_index(op.f('ix_extraction_runs_document_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_eligibility_results_supplier_id'), table_name='eligibility_results')
    op.drop_index(op.f('ix_eligibility_results_case_id'), table_name='eligibility_results')
    op.drop_table('eligibility_results')
    op.drop_index(op.f('ix_eligibility_checks_supplier_id'), table_name='eligibility_checks')
    op.drop_index(op.f('ix_eligibility_checks_requirement_id'), table_name='eligibility_checks')
    op.drop_index(op.f('ix_eligibility_checks_case_id'), table_name='eligibility_checks')
    op.drop_table('eligibility_checks')
    op.drop_index(op.f('ix_documents_supplier_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decision_summaries_case_id'), table_name='decision_summaries')
    op.drop_table('decision_summaries')
    op.drop_index(op.f('ix_suppliers_case_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_requirements_case_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_ranking_scenarios_case_id'), table_name='ranking_scenarios')
    op.drop_table('ranking_scenarios')
    op.drop_table('sourcing_cases')
    # ### end Alembic commands ###
