"""Add provenance fields to Evidence

Revision ID: b18e408ebf3a
Revises: bfa38df8b845
Create Date: 2026-08-09 14:02:49.991913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18e408ebf3a'
down_revision = 'bfa38df8b845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('provenance_method', sa.String(length=50), nullable=True))
    op.add_column('evidence', sa.Column('validation_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'validation_reason')
    op.drop_column('evidence', 'provenance_method')
    # ### end Alembic commands ###
